week 1 course python
airlab-unsri/basic-python-course pull request #12
Opened 2019-11-14 13:31 UTC by rzkibar

2019-11-14 13:55 UTC, ariefrahmansyah requested changes
can you rename the file to `course_1.py`

using `#` as filename is not good practice

2019-11-14 14:17 UTC, rzkibar commented
> can you rename the file to `course_1.py`
> 
> using `#` as filename is not good practice



> can you rename the file to `course_1.py`
> 
> using `#` as filename is not good practice

my bad.. udah diubah kak

2019-11-14 14:18 UTC, rzkibar commented
> can you rename the file to `course_1.py`
> 
> using `#` as filename is not good practice

my bad.. udah diubah kak

2019-11-14 14:51 UTC, ariefrahmansyah requested changes

2019-11-14 14:51 UTC, ariefrahmansyah commented on rzkibar/list_compre
> +numbers = [10, 20, 30]
you need to add .py extension here :)

2019-11-14 14:51 UTC, ariefrahmansyah commented on rzkibar/list_looping
> +students = ["baba", "bibi", "bubu", "bobo"]
you need to add .py extension here :)

2019-11-15 02:17 UTC, ariefrahmansyah approved these changes
LGTM! Mantapp

2019-11-15 02:17 UTC, merged