add  declare variables
airlab-unsri/basic-python-course pull request #3
Opened 2019-11-06 02:18 UTC by AhmadAgus2010

2019-11-06 04:06 UTC, imambungo requested changes

2019-11-06 04:06 UTC, imambungo commented on README.md
> +e = false          # a boolean
di Python, boolean diawali dengan huruf besar.  
`True` bukan `true`.  
 `False` bukan `false`.

Bakalan error kalo huruf pertamony pake huruf kecil.

2019-11-06 04:08 UTC, imambungo commented on README.md
> +e = false          # a boolean
@AhmadAgus2010 Tolong diupdate mad

2019-11-06 04:13 UTC, imambungo commented on README.md
> +g = 2+3j           # a complex
@AhmadAgus2010 mad, ini dapat dari mn? bs minta link referensiny dk?

2019-11-06 04:17 UTC, imambungo reviewed
Bagusny waktu bikin list atau tuple elemen2ny diselipkan spasi, biar rapi dan enak dilihat.

2019-11-06 04:17 UTC, imambungo commented on README.md
> +h = [1,2,3,4]      # a list
```suggestion
h = [1, 2, 3, 4]   # a list
```

2019-11-06 04:17 UTC, imambungo commented on README.md
> +i = ("w","o","r","l","d") # a tuple
```suggestion
i = ("w", "o", "r", "l", "d") # a tuple
```

2019-11-07 16:45 UTC, defrianafandi reviewed
Good @imambungo

2019-11-08 14:30 UTC, ariefrahmansyah commented on README.md
> +a = 'some text'    # declare a string variable
Ubah dong dari `a = 'some text'` jadi `a = 'ini adalah string'`

2019-11-13 07:21 UTC, AhmadAgus2010 commented on README.md
> +e = false          # a boolean
oke mam, baru ku update . hehe

2019-11-14 03:28 UTC, ariefrahmansyah requested changes
Wuoohhhh, mantabbbb @AhmadAgus2010!
Thanks for the pull request! This is really good pull request!

Btw, can you fix the merge conflict on README.md? You can refer to this guide: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-on-github

2019-11-15 02:24 UTC, ariefrahmansyah approved these changes
Alright, LGTM! Thanks for your work!

2019-11-15 02:24 UTC, merged